export const challengeData = [
  {
    title: "파이썬 초급",
    category: "backend",
    type: "official",
    url: "https://docs.python.org/3/tutorial/index.html",
    dueDate: "2025-06-05T23:59:59Z",
    maximum: 10,
    description: "파이썬 초급",
    id: "1",
    userId: "3",
  },
  {
    title: "리액트 hooks",
    category: "frontend",
    type: "article",
    url: "https://reactjs.org/docs/hooks-intro.html",
    dueDate: "2025-06-07T23:59:59Z",
    maximum: 11,
    description: "리액트 hooks",
    id: "2",
    userId: "18",
  },
  {
    title: "Node.js 비동기 프로그래밍",
    category: "backend",
    type: "official",
    url: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/",
    dueDate: "2025-06-09T23:59:59Z",
    maximum: 12,
    description: "Node.js 비동기 프로그래밍",
    id: "3",
    userId: "5",
  },
  {
    title: "Django 기초",
    category: "backend",
    type: "official",
    url: "https://docs.djangoproject.com/en/4.0/intro/",
    dueDate: "2025-06-11T23:59:59Z",
    maximum: 13,
    description: "Django 기초",
    id: "4",
    userId: "10",
  },
  {
    title: "Docker 시작하기",
    category: "devops",
    type: "official",
    url: "https://docs.docker.com/get-started/",
    dueDate: "2025-06-13T23:59:59Z",
    maximum: 14,
    description: "Docker 시작하기",
    id: "5",
    userId: "2",
  },
  {
    title: "Next.js App Router",
    category: "frontend",
    type: "article",
    url: "https://nextjs.org/docs/app/building-your-application/routing",
    dueDate: "2025-06-15T23:59:59Z",
    maximum: 10,
    description: "Next.js App Router",
    id: "6",
    userId: "4",
  },
  {
    title: "Jest test framework",
    category: "test",
    type: "official",
    url: "https://jestjs.io/docs/getting-started",
    dueDate: "2025-06-17T23:59:59Z",
    maximum: 11,
    description: "Jest test framework",
    id: "7",
    userId: "2",
  },
];

export const challengeStatusData = [
  {
    challengeId: "1",
    state: "ACCEPTED",
  },
  {
    challengeId: "2",
    state: "ACCEPTED",
  },
  {
    challengeId: "3",
    state: "ACCEPTED",
  },
  {
    challengeId: "4",
    state: "ACCEPTED",
  },
  {
    challengeId: "5",
    state: "ACCEPTED",
  },
  {
    challengeId: "6",
    state: "ACCEPTED",
  },
  {
    challengeId: "7",
    state: "ACCEPTED",
  },
];
